import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("test", "routes/test.tsx"),
  route("process", "routes/process.tsx"),
  route("testimonials", "routes/testimonials.tsx"),
  route("meet-the-team", "routes/meet-the-team.tsx"),
  route("faqs", "routes/faqs.tsx"),
  route("blog", "routes/blog.tsx"),
  route("market-insights", "routes/market-insights.tsx"),
  route("sell-my-house-fast-las-vegas", "routes/sell-my-house-fast-las-vegas.tsx"),
  route("sell-my-house-fast-southern-california", "routes/sell-my-house-fast-southern-california.tsx"),
  route("sell-my-house-fast-orange-county", "routes/sell-my-house-fast-orange-county.tsx"),
  route("sell-my-house-fast-san-diego", "routes/sell-my-house-fast-san-diego.tsx"),
  route("sell-my-house-fast-riverside", "routes/sell-my-house-fast-riverside.tsx"),
  route("sell-my-house-fast-inland-empire", "routes/sell-my-house-fast-inland-empire.tsx"),
  route("sellers", "routes/sellers.tsx"),
  route("buyers", "routes/buyers.tsx"),
  route("investors", "routes/investors.tsx"),
  route("neighborhoods", "routes/neighborhoods.tsx"),
  route("about", "routes/about.tsx"),
  route("contact", "routes/contact.tsx"),
  route("thank-you", "routes/thank-you.tsx"),
  route("privacy-policy", "routes/privacy-policy.tsx"),
  route("terms-of-service", "routes/terms-of-service.tsx"),
  route("company-history", "routes/company-history.tsx"),
  route("fast-home-cash-offers-usa", "routes/fast-home-cash-offers-usa.tsx"),
  route("fast-home-cash-offers-reviews", "routes/fast-home-cash-offers-reviews.tsx"),
  route("fast-home-cash-offers-near-me", "routes/fast-home-cash-offers-near-me.tsx"),
  route("fast-home-cash-offers-las-vegas", "routes/fast-home-cash-offers-las-vegas.tsx"),
  route("fast-home-cash-offers-nevada", "routes/fast-home-cash-offers-nevada.tsx"),
  route("fast-home-offer", "routes/fast-home-offer.tsx"),
  route("opendoor-cash-offer", "routes/opendoor-cash-offer.tsx"),
  route("zillow-cash-offer", "routes/zillow-cash-offer.tsx"),
  // Catch-all route for 404 errors
  route("*", "routes/404.tsx"),
] satisfies RouteConfig;
